### ISSUE TITLE
Override should be optional

### ISSUE THREAD

**Issue by JoeBengalen** [geggleto/method-override#1]
Hellow, In the current implementation you just assume `_method` is available. Shouldn't a check happen before update the actual requst?

https://github.com/geggleto/method-override/blob/master/src/MethodOverrideMiddleware.php#L33

Also I guess your variables should not be named `$requestInterface`, but just `$request`. Same for response.

**Comment by geggleto** [comment]
Suppose we could set-up the key to be a config setting. The _method was to mimic the ability to override POST stuff in Slim 2.

**Comment by geggleto** [comment]
See https://github.com/geggleto/method-override/commit/64b2bd4859bc52b2d1f164cdb52b6d3530736627
